[package]
name = "example-openssl"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_openssl"
path = "src/main.rs"
doc = false

[target.'cfg(not(windows))'.dependencies]
tsukuyomi = { version = "0.4.0-dev", features = ["use-openssl"] }
openssl = "0.10"
