[package]
name = "tsukuyomi"
description = """
Asynchronous Web framework for Rust
"""
version = "0.4.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"
readme = "README.md"
keywords = ["web", "framework", "futures", "hyper", "tokio"]
categories = ["web-programming::http-server"]

build = "build.rs"

include = [
  "src/**/*.rs",
  "tests/**/*.rs",
  "benches/**/*.rs",
  "examples/**/*.rs",
  "build.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-MIT",
  "LICENSE-APACHE",
]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = [
  "secure",
  "tls",
  "websocket",
]

[dependencies]
bytes = "0.4"
cookie = { version = "0.11", features = ["percent-encode"] }
either = "1.5"
failure = "0.1.2"
filetime = "0.2"
futures = "0.1"
http = "0.1"
indexmap = "1"
log = "0.4"
mime = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "0.3"
serde_urlencoded = "0.5"
time = "0.1"
tower-service = "0.1"
url = "1.7.1"
uuid = "0.7.1"

[dependencies.tsukuyomi-internal]
version = "0.4.0-dev" # <cargo-version-sync>
path = "./internal"

[dependencies.tsukuyomi-macros]
version = "0.4.0-dev" # <cargo-version-sync>
path = "./macros"

[dependencies.tsukuyomi-server]
version = "0.4.0-dev" # <cargo-version-sync>
path = "./server"

[dev-dependencies]
cookie = "0.11"
either = "1"
matches = "0.1"
time = "0.1"
serde = { version = "1", features = ["derive"] }
cargo-version-sync = { version = "0.0.5", default-features = false }

[features]
default = []
secure = ["cookie/secure"]
tls = ["tsukuyomi-server/tls"]


# ==== START cargo-version-sync ====

[[package.metadata.version-sync.replacements]]
file = "Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "internal/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "macros/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "server/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

# ==== END cargo-version-sync ====
