[package]
name = "test-askama"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[lib]
doc = false

[dependencies]
askama = "0.7.2"
tsukuyomi = { path = "../..", features = ["with-askama"] }
