[package]
name = "example-tower-middleware"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_tower_middleware"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { version = "0.4.0", features = ["tower-middleware"] }
tower-web = { version = "0.3", default-features = false }
pretty_env_logger = "0.2"
log = "0.4.6"
