dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true
  - bundler: true
  - directories:
    - doc/target

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      sudo: required
      addons:
        apt:
          packages:
            - libssl-dev
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test
        - cargo test --no-default-features
        # examples
        - cargo test -p basic
        - cargo test -p git-server
        - cargo test -p json
        - cargo test -p lines
        - cargo test -p routing
        - cargo test -p session
        - cargo test -p unix-socket
      after_success:
        - cargo fmt -- --write-mode=diff
        - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        - USE_SKEPTIC=1 cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    - rust: beta
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test
        - cargo test --no-default-features
        # examples
        - cargo test -p basic
        - cargo test -p git-server
        - cargo test -p json
        - cargo test -p lines
        - cargo test -p routing
        - cargo test -p session
        - cargo test -p unix-socket
      after_success:
        - cargo fmt -- --write-mode=diff

    - rust: nightly
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test
        - cargo test --no-default-features
        - cargo test --features nightly
        # examples
        - cargo test -p async-await
        - cargo test -p basic
        - cargo test -p git-server
        - cargo test -p json
        - cargo test -p lines
        - cargo test -p routing
        - cargo test -p session
        - cargo test -p unix-socket
      after_success:
        - cargo fmt -- --write-mode=diff

    - rust: stable
      env: DEPLOY_DOC
      script:
        - cargo clean
        - cargo doc
        - rm -f target/doc/.lock
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: ubnt-intrepid/tsukuyomi
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
