dist: trusty
sudo: false
language: rust

cache:
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+$/
    - /^wip\/.*$/

script:
  - cargo update
  - cargo build

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: beta
      env: TSUKUYOMI_DENY_WARNINGS=1
      before_script:
        - rustup component add rustfmt-preview clippy-preview
      script:
        - cargo update
        - cargo fmt -- --check
        - cargo clippy --tests
        - cargo test
        - cargo test --no-default-features
        - cargo test --features full

    # - rust: 1.30.0
    - rust: beta
      os: osx
    - rust: beta
      os: windows
    # - rust: beta
    - rust: nightly

    # FIXME: enable before releasing 0.3.0
    # - rust: stable
    #   env: EXAMPLES
    #   script:
    #     - cargo clean
    #     - |
    #         git clone https://github.com/tsukuyomi-rs/examples.git ./examples --depth 1 -b 0.2.x
    #         echo '[patch.crates-io]' >> examples/Cargo.toml
    #         echo 'tsukuyomi = { path = ".." }' >> examples/Cargo.toml
    #     - (cd examples && cargo test -p example-basic)
    #     - (cd examples && cargo test -p example-diesel)
    #     - (cd examples && cargo test -p example-json)
    #     - (cd examples && cargo test -p example-juniper)
    #     - (cd examples && cargo test -p example-lines)
    #     - (cd examples && cargo test -p example-routing)
    #     - (cd examples && cargo test -p example-unix-socket)
    #
    # - rust: nightly-2018-07-08
    #   env: EXAMPLES_NIGHTLY_ONLY
    #   script:
    #     - cargo clean
    #     - |
    #         git clone https://github.com/tsukuyomi-rs/examples.git ./examples --depth 1 -b 0.2.x
    #         echo '[patch.crates-io]' >> examples/Cargo.toml
    #         echo 'tsukuyomi = { path = ".." }' >> examples/Cargo.toml
    #     - (cd examples && cargo test -p example-async-await)
    #     - (cd examples && cargo test -p example-git-server)
    #
    # - rust: nightly
    #   env: DOCTEST
    #   script:
    #     - cargo clean
    #     - |
    #         git clone https://github.com/tsukuyomi-rs/docs.git ./docs --depth 1 -b 0.2.x
    #         echo '[patch.crates-io]' >> docs/Cargo.toml
    #         echo 'tsukuyomi = { path = ".." }' >> docs/Cargo.toml
    #     - (cd docs && cargo test --all)

    - rust: beta # FIXME: switch to stable
      env: DEPLOY_API_DOC
      script:
        - cargo clean
        - cargo doc --features full
        - cargo doc -p tsukuyomi-codegen
        - rm -f target/doc/.lock
        - echo '<meta http-equiv="refresh" content="0;URL=tsukuyomi/index.html">' > target/doc/index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: tsukuyomi-rs/tsukuyomi
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
