dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true
  - bundler: true
  - directories:
    - doc/target

branches:
  only:
    - master
    - /^\d+\.\d+$/
    - /^wip\/.*$/

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      sudo: required
      env: RUSTFLAGS="-D warnings"
      addons:
        apt:
          packages:
            - libssl-dev
            - pkg-config
            - cmake
            - zlib1g-dev
      before_script:
        - rustup component add rustfmt-preview
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "cargo-tarpauling is installed."
      script:
        - cargo clean
        - cargo test
        - cargo test --no-default-features
        # contrib
        - cargo test -p tsukuyomi-juniper
        # examples
        - cargo test -p example-basic
        - cargo test -p example-diesel
        - cargo test -p example-json
        - cargo test -p example-juniper
        - cargo test -p example-lines
        - cargo test -p example-routing
        - cargo test -p example-unix-socket
      after_success:
        - cargo fmt -- --write-mode=diff
        # - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        - |
            cargo tarpaulin --skip-clean --ciserver travis-ci --coveralls $TRAVIS_JOB_ID \
                --packages tsukuyomi \
                           tsukuyomi-juniper

    - rust: beta
      env: RUSTFLAGS="-D warnings"
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test
        - cargo test --no-default-features
        # contrib
        - cargo test -p tsukuyomi-juniper
        # examples
        - cargo test -p example-basic
        - cargo test -p example-diesel
        - cargo test -p example-json
        - cargo test -p example-juniper
        - cargo test -p example-lines
        - cargo test -p example-routing
        - cargo test -p example-unix-socket
      after_success:
        - cargo fmt -- --write-mode=diff

    - rust: nightly
      env: RUSTFLAGS="-D warnings"
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test
        - cargo test --no-default-features
        #- cargo test --features nightly
        - cargo test -p tsukuyomi-codegen
        # contrib
        - cargo test -p tsukuyomi-juniper
        # doctest
        - cargo test -p doctest
        # examples
        - cargo test -p example-basic
        - cargo test -p example-diesel
        - cargo test -p example-json
        - cargo test -p example-juniper
        - cargo test -p example-lines
        - cargo test -p example-routing
        - cargo test -p example-unix-socket
        # works only on nightly channel
        - cargo test -p example-async-await
        - cargo test -p example-git-server
      after_success:
        - cargo fmt -- --write-mode=diff

    - rust: nightly-2018-06-28
      env: DEPLOY_DOC
      script:
        - cargo clean
        # FIXME: remove `--no-deps` as soon as all errors from dependencies are removed.
        - cargo doc --features "secure tls codegen" --no-deps
        - cargo doc -p tsukuyomi-codegen --no-deps
        - cargo doc -p tsukuyomi-juniper --no-deps
        - cargo doc -p tsukuyomi-template --no-deps
        - rm -f target/doc/.lock
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: ubnt-intrepid/tsukuyomi
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
