dist: trusty
sudo: false
language: rust

cache:
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+$/

script: >-
  cargo update &&
  rake ci:fast


matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: beta
    - rust: nightly
    - rust: 1.30.0

    - rust: stable
      before_script:
        - rustup component add rustfmt-preview clippy-preview
      script: >-
        cargo update &&
        rake ci:strict
      before_deploy: >-
        rm -rf target/doc &&
        cargo update &&
        cargo doc --all-features --no-deps -p failure -p tungstenite -p tokio-tungstenite -p walkdir &&
        cargo doc --all-features --no-deps -p tsukuyomi-server &&
        cargo doc --all-features --no-deps &&
        rm -f target/doc/.lock &&
        (echo '<meta http-equiv="refresh" content="0;URL=tsukuyomi/index.html">' > target/doc/index.html)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: tsukuyomi-rs/tsukuyomi
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
