resources:
  containers:
    - container: rust
      image: ubntintrepid/tsukuyomi:latest
    - container: tarpaulin
      image: xd009642/tarpaulin:latest-nightly
      options: --security-opt seccomp=unconfined

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain stable
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        rustup --version
        rustc --version
        cargo --version
        rake --version
      displayName: 'Install Rust Toolchain'
    - script: rake ci:fast
      displayName: 'Run Test Script'

  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - script: |
        curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        rustup --version
        rustc --version
        cargo --version
        rake --version
      displayName: 'Install Rust Toolchain'
    - script: rake ci:fast
      displayName: 'Run Test Script'

  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        rust:
          containerResource: rust
        tarpaulin:
          containerResource: tarpaulin
    container: $[ variables['containerResource'] ]
    steps:
    - script: |
        rustup --version
        rake --version
      displayName: 'Show installed tools version'
      condition: eq(variables['containerResource'], 'rust')

    - script: |
        rustup toolchain install stable beta nightly 1.30.0
        rustup component add rustfmt-preview clippy-preview --toolchain stable
      displayName: 'Install required toolchains and components'
      condition: eq(variables['containerResource'], 'rust')

    - script: rake ci:strict
      displayName: 'Run test on stable channel'
      env:
        RUSTUP_TOOLCHAIN: stable
        CARGO_TERM_VERBOSE: true
      condition: eq(variables['containerResource'], 'rust')

    - script: rake ci:deploy_doc
      displayName: 'Deploy API doc'
      env:
        RUSTUP_TOOLCHAIN: stable
        CARGO_TERM_VERBOSE: true
        GH_TOKEN: $(myGitHubToken)
        SOURCE_BRANCH_NAME: $(variables['Build.SourceBranchName'])
      condition: eq(variables['containerResource'], 'rust')

    - script: rake ci:fast
      displayName: 'Build on beta channel'
      env:
        RUSTUP_TOOLCHAIN: beta
        CARGO_TERM_VERBOSE: true
      condition: eq(variables['containerResource'], 'rust')

    - script: rake ci:fast || true
      displayName: 'Build on nightly channel'
      env:
        RUSTUP_TOOLCHAIN: nightly
        CARGO_TERM_VERBOSE: true
      condition: eq(variables['containerResource'], 'rust')

    - script: rake ci:fast
      displayName: 'Build on minimum supported channel'
      env:
        RUSTUP_TOOLCHAIN: 1.30.0
        CARGO_TERM_VERBOSE: true
      condition: eq(variables['containerResource'], 'rust')

    - script: |
        cargo tarpaulin --all-features --out Xml
        bash <(curl -s https://codecov.io/bash)
      displayName: 'Run tarpaulin'
      env:
        CODECOV_TOKEN: $(myCodecovToken)
      condition: eq(variables['containerResource'], 'tarpaulin')
