[package]
name = "tsukuyomi"
description = """
A next generation Web framework for Rust
"""
version = "0.3.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"
readme = "README.md"
keywords = ["web", "framework", "futures", "hyper", "tokio"]
categories = ["web-programming::http-server"]

build = "build.rs"

include = [
  "src/**/*.rs",
  "tests/**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-*",
]

[package.metadata.docs.rs]
features = [
  "secure",
  "tls",
  "websocket",
]
# FIXME: remove it as soon as the rustc version used in docs.rs is updated
rustdoc-args = ["--cfg", "tsukuyomi_inject_extern_prelude"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
hyper = { version = "0.12.5", features = ["runtime"], default-features = false }
http = "0.1.5"
mime = "0.3.7"
bytes = "0.4.8"
tokio = "0.1.7"
tokio-tcp = "0.1.0"
tokio-threadpool = "0.1.5"
futures = "0.1.21"
failure = { version = "0.1.1", features = ["derive"] }
log = "0.4.2"
rustls = { version = "0.14.0", optional = true }
tokio-rustls = { version = "0.8.0", optional = true }
cookie = { version = "0.11.0", features = ["percent-encode"] }
serde = { version = "1.0.66", features = ["derive"] }
serde_json = "1.0.20"
indexmap = "1.0.1"
filetime = "0.2.1"
time = "0.1.40"
either = "1.5.0"

# for WebSocket
base64 = { version = "0.9.2", optional = true }
sha1 = { version = "0.6.0", optional = true }
tungstenite = { version = "0.6.0", optional = true }
tokio-tungstenite = { version = "0.6.0", optional = true }

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.2.0"

[dev-dependencies]
matches = "0.1.6"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
default = []
secure = ["cookie/secure"]
tls = ["rustls", "tokio-rustls"]
websocket = ["base64", "sha1", "tungstenite", "tokio-tungstenite"]
