[package]
name = "ganymede"
version = "0.1.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[dependencies]
hyper = { version = "0.12.1", features = ["runtime"], default-features = false }
http = "0.1.5"
mime = "0.3"
bytes = "0.4"
tokio = "0.1"
futures = "0.1"
failure = { version = "0.1", features = ["derive"] }
log = "*"
scoped-tls = "*"

[dev-dependencies]
pretty_env_logger = "*"
tokio-io = "*"
