[package]
name = "tsukuyomi"
description = """
An asynchronous Web framework for Rust
"""
version = "0.4.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"
readme = "README.md"
keywords = ["web", "framework", "futures", "hyper", "tokio"]
categories = ["web-programming::http-server"]

build = "build.rs"

include = [
  "src/**/*.rs",
  "tests/**/*.rs",
  "benches/**/*.rs",
  "examples/**/*.rs",
  "build.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-MIT",
  "LICENSE-APACHE",
]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = [
  "secure",
  "tls",
  "websocket",
]

# ==== START cargo-version-sync ====

[package.metadata.version-sync]
use-preset = false

[[package.metadata.version-sync.replacements]]
file = "Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "tsukuyomi-internal/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]


[[package.metadata.version-sync.replacements]]
file = "tsukuyomi-internal-macros/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "src/lib.rs"
replacers = [
  { type = "builtin", target = "html-root-url" }
]

[[package.metadata.version-sync.replacements]]
file = "README.md"
replacers = [
  { type = "regex", search = "{{name}} = \"[0-9a-z\\.-]+\"", replace = "{{name}} = \"{{version}}\"" },
  { type = "regex", search = "https://deps.rs/crate/{{name}}/[a-z0-9\\.-]+", replace = "https://deps.rs/crate/{{name}}/{{version}}" },
]

# ==== END cargo-version-sync ====

[dependencies]
bytes = "0.4"
failure = "0.1.2"
filetime = "0.2"
futures = "0.1"
http = "0.1"
mime = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "0.3"
serde_urlencoded = "0.5"
time = "0.1"
walkdir = "2"

# for WebSocket
base64 = { version = "0.10", optional = true }
sha-1 = { version = "0.8", optional = true }
tokio-tungstenite = { version = "0.6", optional = true }
tungstenite = { version = "0.6", optional = true }

# for Askama
askama = { version = "0.7", optional = true }
mime_guess = { version = "2.0.0-alpha.6", optional = true }

[dev-dependencies]
cookie = "0.11"
either = "1"
cargo-version-sync = { version = "0.0.4", default-features = false }

[dependencies.tsukuyomi-internal]
version = "0.4.0-dev" # <cargo-version-sync>
path = "tsukuyomi-internal"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
default = []
secure = [
  "tsukuyomi-internal/secure",
]
tls = [
  "tsukuyomi-internal/tls",
]
websocket = [
  "base64",
  "sha-1",
  "tokio-tungstenite",
  "tungstenite",
]
with-askama = [
  "askama",
  "mime_guess",
]

[workspace]
members = [
  "tsukuyomi-internal",
  "tsukuyomi-internal-macros",

  "testcrates/doctest",
  "testcrates/askama",
]
