[package]
name = "tsukuyomi"
description = """
An asynchronous Web framework for Rust
"""
version = "0.3.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"
readme = "README.md"
keywords = ["web", "framework", "futures", "hyper", "tokio"]
categories = ["web-programming::http-server"]

build = "build.rs"

include = [
  "src/**/*.rs",
  "tests/**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-*",
]

[package.metadata.docs.rs]
features = [
  "secure",
  "tls",
  "websocket",
]
# FIXME: remove it as soon as the rustc version used in docs.rs is updated
rustdoc-args = ["--cfg", "tsukuyomi_inject_extern_prelude"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "0.4.8"
cookie = { version = "0.11.0", features = ["percent-encode"] }
either = "1.5.0"
failure = "0.1.2"
filetime = "0.2.1"
futures = "0.1.21"
http = "0.1.5"
hyper = { version = "0.12.5", default-features = false }
indexmap = "1.0.1"
mime = "0.3.7"
log = "0.4.2"
serde = { version = "1.0.66", features = ["derive"] }
serde_json = "1.0.20"
time = "0.1.40"
tokio-io = "0.1.9"

tsukuyomi-server = { version = "0.1.0", path = "tsukuyomi-server" }

# for WebSocket
base64 = { version = "0.9.2", optional = true }
sha1 = { version = "0.6.0", optional = true }
tokio-tungstenite = { version = "0.6.0", optional = true }
tungstenite = { version = "0.6.0", optional = true }

[dev-dependencies]
matches = "0.1.6"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
default = []
secure = [
  "cookie/secure",
]
tls = [
  "tsukuyomi-server/tls",
]
websocket = [
  "base64",
  "sha1",
  "tokio-tungstenite",
  "tungstenite",
]

[workspace]
members = [
  "tsukuyomi-server",
]
