[package]
name = "tsukuyomi"
description = """
Asynchronous Web framework for Rust
"""
version = "0.4.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"
readme = "README.md"
keywords = ["web", "framework", "futures", "hyper", "tokio"]
categories = ["web-programming::http-server"]

build = "build.rs"

include = [
  "src/**/*.rs",
  "tests/**/*.rs",
  "benches/**/*.rs",
  "examples/**/*.rs",
  "build.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-MIT",
  "LICENSE-APACHE",
]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = [
  "secure",
  "tls",
  "websocket",
]

[dependencies]

[dependencies.tsukuyomi-internal-core]
version = "0.4.0-dev" # <cargo-version-sync>
path = "internal/core"

[dependencies.tsukuyomi-internal-runtime]
version = "0.4.0-dev" # <cargo-version-sync>
path = "internal/runtime"

[dev-dependencies]
cookie = "0.11"
either = "1"
futures = "0.1"
http = "0.1"
time = "0.1"
serde = { version = "1", features = ["derive"] }
cargo-version-sync = { version = "0.0.5", default-features = false }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
default = []
secure = ["tsukuyomi-internal-core/secure"]
tls = ["tsukuyomi-internal-runtime/tls"]

[workspace]
members = [
  "./",
  "internal/core",
  "internal/macros",
  "internal/runtime",
  "testcrates/doctest",
  "toolkit",
  "toolkit/macros",
]

# ==== START cargo-version-sync ====

[package.metadata.version-sync]
use-preset = false

[[package.metadata.version-sync.replacements]]
file = "Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "internal/core/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "internal/macros/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "internal/runtime/Cargo.toml"
replacers = [
  { type = "regex", search = "version = \"[0-9a-z\\.-]+\" # <cargo-version-sync>", replace = "version = \"{{version}}\" # <cargo-version-sync>" }
]

[[package.metadata.version-sync.replacements]]
file = "src/lib.rs"
replacers = [
  { type = "builtin", target = "html-root-url" }
]

[[package.metadata.version-sync.replacements]]
file = "README.md"
replacers = [
  { type = "regex", search = "{{name}} = \"[0-9a-z\\.-]+\"", replace = "{{name}} = \"{{version}}\"" },
  { type = "regex", search = "https://deps.rs/crate/{{name}}/[a-z0-9\\.-]+", replace = "https://deps.rs/crate/{{name}}/{{version}}" },
]

# ==== END cargo-version-sync ====
