[package]
name = "tsukuyomi"
description = """
An asynchronous Web framework for Rust
"""
version = "0.3.2"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"
readme = "README.md"
keywords = ["web", "framework", "futures", "hyper", "tokio"]
categories = ["web-programming::http-server"]

build = "build.rs"

include = [
  "src/**/*.rs",
  "tests/**/*.rs",
  "benches/**/*.rs",
  "examples/**/*.rs",
  "build.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-MIT",
  "LICENSE-APACHE",
]

[package.metadata.docs.rs]
features = [
  "secure",
  "tls",
  "websocket",
]
# FIXME: remove it as soon as the rustc version used in docs.rs is updated
rustdoc-args = ["--cfg", "tsukuyomi_inject_extern_prelude"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
tsukuyomi-codegen = { version = "0.1.0", path = "tsukuyomi-codegen" }

bytes = "0.4"
cookie = { version = "0.11", features = ["percent-encode"] }
derive_more = "0.13"
either = "1.5"
failure = "0.1.2"
filetime = "0.2"
futures = "0.1"
http = "0.1"
indexmap = "1"
mime = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "0.3"
serde_urlencoded = "0.5"
time = "0.1"
tower-service = "0.1"
tsukuyomi-server = "0.1"
walkdir = "2"

# for WebSocket
base64 = { version = "0.9", optional = true }
sha-1 = { version = "0.8", optional = true }
tokio-tungstenite = { version = "0.6", optional = true }
tungstenite = { version = "0.6", optional = true }

# for Askama
askama = { version = "0.7", optional = true }
mime_guess = { version = "2.0.0-alpha.6", optional = true }

[dev-dependencies]
matches = "0.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
default = []
secure = [
  "cookie/secure",
]
tls = [
  "tsukuyomi-server/tls",
]
websocket = [
  "base64",
  "sha-1",
  "tokio-tungstenite",
  "tungstenite",
]

[workspace]
members = [
  "tsukuyomi-codegen",
]
