[package]
name = "ganymede"
version = "0.1.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[dependencies]
hyper = { version = "0.12.1", features = ["runtime"], default-features = false }
http = "0.1.5"
mime = "0.3"
bytes = "0.4"
tokio = "0.1"
tokio-tcp = "0.1"
futures = "0.1"
failure = { version = "0.1", features = ["derive"] }
log = "*"
scoped-tls = "*"
rustls = { version = "0.11", optional = true }
tokio-rustls = { version = "0.4", optional = true }
fnv = "*"

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.2"

[dev-dependencies]
pretty_env_logger = "*"
tokio-io = "*"

[features]
default = ["tls"]
tls = ["rustls", "tokio-rustls"]
