[package]
name = "tsukuyomi-rt"
version = "0.1.0-dev"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"

[dev-dependencies]
version-sync = "0.6"
