[package]
name = "example-rustls"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_rustls"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { version = "0.5.0-dev" }
tsukuyomi-server = { version = "0.2.0-dev", features = ["use-rustls"] }
rustls = "0.14"
tokio-rustls = "0.8"
failure = "0.1.3"
