[package]
name = "template-tera"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "template-tera"
path = "src/main.rs"

[dependencies]
tsukuyomi = { path = "../.." }
tera = "0.11.8"
serde = { version = "1", features = ["derive"] }

[dependencies.tsukuyomi-template]
path = "../../contrib/tsukuyomi-template"
default-features = false
features = ["tera"]
