[package]
name = "tsukuyomi-internal-core"
version = "0.4.0-dev" # <cargo-version-sync>
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

build = "build.rs"

[package.metadata.version-sync]
use-preset = true

[dependencies]
bytes = "0.4"
cookie = { version = "0.11", features = ["percent-encode"] }
derive_more = "0.13"
either = "1.5"
failure = "0.1.2"
futures = "0.1"
http = "0.1"
indexmap = "1"
log = "0.4"
mime = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "0.3"
serde_urlencoded = "0.5"
tower-service = "0.1"

[dependencies.tsukuyomi-internal-runtime]
version = "0.4.0-dev" # <cargo-version-sync>
path = "../runtime"

[dependencies.tsukuyomi-internal-macros]
version = "0.4.0-dev" # <cargo-version-sync>
path = "../macros"

[dev-dependencies]
matches = "0.1"
cargo-version-sync = { version = "0.0.5", default-features = false }

[dev-dependencies.tsukuyomi]
version = "0.4.0-dev" # <cargo-version-sync>
path = "../.."

[features]
secure = [
  "cookie/secure",
]
