[package]
name = "tsukuyomi-macros"
description = "Procerual macros for Tsukuyomi"
version = "0.5.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsukuyomi-rs/tsukuyomi.git"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full", "extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4.20"

[dev-dependencies]
tsukuyomi = { version = "0.5", path = ".." }
