[package]
name = "example-tls-rustls"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_tls_rustls"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { version = "0.4.0-dev", features = ["use-rustls"] }
rustls = "0.14"
tokio-rustls = "0.8"
failure = "0.1.3"

