[package]
name = "doctest"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[lib]
name = "doctest"
path = "lib.rs"
doc = false

[dev-dependencies]
tsukuyomi = { version = "0.2.0-dev", path = ".." }
futures = "0.1"
futures-await = "0.1"
