[package]
name = "example-websocket"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_websocket"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { path = "../../tsukuyomi" }
tsukuyomi-tungstenite = { path = "../../tsukuyomi-tungstenite" }
izanami = "0.1.0-preview.2"
futures = "0.1.21"
exitfailure = "0.5"
uuid = { version = "0.7", features = ["v4"] }
