[package]
name = "example-session-redis"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_session_redis"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { path = "../../tsukuyomi" }
izanami = "0.1.0-preview.1"
tsukuyomi-session = { path = "../../tsukuyomi-session", features = ["use-redis"] }
either = "1"
serde = { version = "1", features = ["derive"] }
redis = "0.9"
