[package]
name = "example-cors"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "example_cors"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = "0.4.0"
tsukuyomi-cors = "0.1.0"
serde = { version = "1", features = ["derive"] }
