[package]
name = "session"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "session"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { path = "../..", features = ["session"] }
