[package]
name = "tsukuyomi-toolkit-macros"
version = "0.1.0" # <cargo-version-sync>
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false
build = "build.rs"

[package.metadata.version-sync]
use-preset = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full", "extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4.20"

[dev-dependencies]
cargo-version-sync = { version = "0.0.5", default-features = false }
