[package]
name = "example-juniper"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "juniper"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = { path = "../.." }
juniper = "0.9.0"
http = "0.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.1.21"
tokio-executor = "0.1"
tokio-threadpool = "0.1"
failure = { version = "0.1.1", features = ["derive"] }
